### ISSUE TITLE
Wrong Terminology used for 'Dens' 

### ISSUE THREAD

**Issue by Leanny** [RaphGG/den-bot#21]
The term 'Den' is used wrong here. What the numbers represent are 'Nests'. Serebii has been spreading this term wrong since the beginning, while internally and in all datamines, rng tools, etc this is called 'Nest'. A den is the object with a fixed location and is unique. Every den had 2 nest, one for common and one for rare beams.

Here an example from the original datamine, referring to all entries with a 'Nest ID': https://twitter.com/Kaphotics/status/1194088327206625281?s=19

**Comment by RaphGG** [comment]
Oh you're absolutely right. Would it be too late to change this within the bot? I think using the terminology of a nest however would just end up confusing almost everyone that utilizes the bot. Not only that, but the bot links to Serebii's webpages for more info on the "dens" where they also use the same terminology.
