### ISSUE TITLE
Add matchup function?

### ISSUE THREAD

**Issue by iMaxed0ut** [RaphGG/den-bot#31]
Type for example “%matchup fire“ and it tells you “Fire type Pokémon are weak to water, ground, and rock!”

Code from another similar open source bot, WigglyBot is below to hopefully make the coding easier. 

    #type matchup
    elif message.content.startswith('%matchup') or message.content.startswith('$matchup'):
      words=message.content.split()
      search=words[1].capitalize()
      if(len(words)!=2):
        msg="Please enter one type at a time!"
      elif search not in types_dict:
        msg="Invalid input!"
      else:
        val=''.join(map(str,types_dict.get(search)))
        msg='For ' + str(search) + ' types, use '+ val.rstrip() + ' type moves!'
      await client.send_message(message.channel, msg)

Here is a link to their GutHub to reference the code and see their files if needed. 
https://github.com/smadler/wigglybot

Edit: Tried to add the “Enhancement” filter/tag but couldn’t find out how ok mobile...sorry!
- [x] Set up either Hard Code or Matrix for Type Matchups

**Comment by RaphGG** [comment]
Just finished implementing the command in a development environment. Will go up to production soon, :) Thanks for the idea!
